services:
  web:
    build: .
    command: opentelemetry-instrument --traces_exporter console --metrics_exporter console --logs_exporter otlp --service_name dice-server flask run -p 8080 --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
  otel:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
    command: ["--config=/etc/otel-collector-config.yaml"]